
service: serverless-devchat

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - cors: true
    timeout: 300
